### PR TITLE
Added flag to skip updating constraints

### PR DESCRIPTION
**Pull request by takahiro0327**
https://github.com/IllusionMods/HSPlugins/issues/51
If everything looks okay, please merge.

This is an implementation of a proposed modification to ShalltyB. Skip updating constraints in ApplyConstraint when flagged.

image

### CODE REVIEW

**Comment by ManlyMarco** [comment]
@ShalltyB

**Comment by ShalltyB** [comment]
Hi, adding the new parameter to the **AddConstraint** method breaks **BetterPenetration** and **ShalltyUtils** _(and maybe others that use NC_)
bp broke

I did it like this: [NodeConstraints.cs - pastebin](https://pastebin.com/u1rJUxgF)

That file also contains the modified UI buttons to move up and down the constraints, if you could also include it please 😋

**Comment by takahiro0327** [comment]
Fixed. Thanks for trying!  
I like the new move button. Added.

Reflection! 
↓me
image

**Comment by takahiro0327** [comment]
@ShalltyB @ManlyMarco 
I've also committed fix #54. I'm sorry, but could you try it while you're at it?

The scope of impact of #54 overlaps with this pull request.
It is related to the order of NodeConstraints and Timelines.

#54 may be as sensitive as this pull request.
It's a separate fix and should be separated into a separate pull request, but I'd like to see them work together.

**Comment by takahiro0327** [comment]
#54 and a summary of amendment.

**Bug Summary**
Objects that were previously tracked by NodeConstraints are no longer tracked.

**Cause**
The processing order of X (Expression_LateUpdate_Patches.Postfix @ Timeline) and Y (Expression_LateUpdate_Patches.Postfix @ NodeConstraints) was changed.
HarmonyBefore and HarmonyAfter were supposed to be processed in the order X -> Y, but GUIDs for Harmony were not specified and HarmonyBefore and HarmonyAfter did not work, resulting in the order Y -> X.

**Fixes:** 
GUID set for Harmony.
https://github.com/IllusionMods/HSPlugins/pull/55/commits/15a16dcee7f7d6f71c48f7cbc4244c6c584edb76

As far as I searched in Github, it was only used to check for plugins. It looks safe. But I don't trust it anymore.
https://github.com/search?q=com.joan6694.illusionplugins.timeline&type=code
https://github.com/search?q=com.joan6694.illusionplugins.nodesconstraints&type=code

**Comment by ShalltyB** [comment]
The DynamicBone fixes seems to be working well 👍

### About  #54:

  Tested in NodeConstraints 1.2.1 / 1.2.2 / 1.2.3.
  
  I tested the linked scene and it worked **with and without** the GUID changes.
  
  
  
  I also **re-saved** the scene in **1.2.1** and loaded it in **1.2.2 / 1.2.3** and it still works, I couldn't reproduce the bug shown in the user videos.

**Comment by ShalltyB** [comment]
My load order is also NodeConstraints -> Timeline in the log and in the BepInEx_Manager 🤔

[output_log.txt](https://github.com/IllusionMods/HSPlugins/files/14025607/output_log.txt)

**Comment by takahiro0327** [comment]
Oops...
I guess the order in which the plugins are loaded has nothing to do with it...

No... in my environment, the order in which plugins are loaded seems to have something to do with the bug.
I added the following to the class definition of NodesConstraints so that NodesConstraints is loaded after the timeline.
```
[BepInDependency("com.joan6694.illusionplugins.timeline")]
```
Then the bug stopped happening without GUID modification.

After the bug was gone, I commented out BepInDependency in NodesConstraints and added BepInDependency to the timeline, and the bug occurred again.
```
//[BepInDependency("com.joan6694.illusionplugins.timeline")]
[BepInDependency("com.joan6694.illusionplugins.nodesconstraints")]]
```

With the bug in place, if the GUID modification is inserted, the bug will no longer occur.

image

**Comment by takahiro0327** [comment]
By the way, if you add the following log with no GUID modification, I can confirm that Postfix in NodesConstraints comes first in my environment.

NodesConstraints.cs(445)
```
        [HarmonyPatch(typeof(Expression), "LateUpdate"), HarmonyAfter("com.joan6694.illusionplugins.timeline")]
        private static class Expression_LateUpdate_Patches
        {
            private static void Postfix()
            {
                _self._currentExpressionIndex++;
                if (_self._currentExpressionIndex == _self._totalActiveExpressions) //Dirty fucking hack that I hate to make sure this runs after *everything*
                {
                    System.Console.WriteLine($"{Time.frameCount:D7} Expression_LateUpdate_Patches(NodesConstraints)");
                    _self.ApplyConstraints();
                } 
            }
        }
```

Timeline.cs(4002)
```
        [HarmonyPatch(typeof(Expression), "LateUpdate"), HarmonyBefore("com.joan6694.illusionplugins.nodesconstraints")]
        private static class Expression_LateUpdate_Patches
        {
            private static void Postfix()
            {
                _self._currentExpressionIndex++;
                if (_self._currentExpressionIndex == _self._totalActiveExpressions)
                {
                    System.Console.WriteLine($"{Time.frameCount:D7} Expression_LateUpdate_Patches(Timeline)");
                    _self.PostLateUpdate();
                }   
            }
        }
```

The order of the patches in a given frame is NodesConstraints -> Timeline.
```
0000326 Expression_LateUpdate_Patches(NodesConstraints)
0000326 Expression_LateUpdate_Patches(Timeline)
0000327 Expression_LateUpdate_Patches(NodesConstraints)
0000327 Expression_LateUpdate_Patches(Timeline)
0000328 Expression_LateUpdate_Patches(NodesConstraints)
0000328 Expression_LateUpdate_Patches(Timeline)
```

When GUID modifications are inserted, Timeline -> NodesConstraints.
```
0001970 Expression_LateUpdate_Patches(Timeline)
0001970 Expression_LateUpdate_Patches(NodesConstraints)
0001971 Expression_LateUpdate_Patches(Timeline)
0001971 Expression_LateUpdate_Patches(NodesConstraints)
0001972 Expression_LateUpdate_Patches(Timeline)
0001972 Expression_LateUpdate_Patches(NodesConstraints)
```

**Comment by ManlyMarco** [comment]
You can use the HarmonyPriority/After/Before attributes to make your patches reliably load before or after another patches. Adding a BepInDependency changes the order that patches are added in, but it does not guarantee that they will stay in that order.

**Comment by takahiro0327** [comment]
Before my fix, HarmonyBefore and HarmonyAfter were not working because the second argument, harmonyInstanceId, of CreateAndPatchAll was not set.
A random GUID was being given to the patch.

fix: https://github.com/IllusionMods/HSPlugins/commit/15a16dcee7f7d6f71c48f7cbc4244c6c584edb76
CreateAndPatchAll: https://github.com/BepInEx/BepInEx.Harmony/blob/0d24abfed64596ee88b4242b9c7e3daa849d6d28/HarmonyX2Interop/Harmony.cs#L313

**Comment by ManlyMarco** [comment]
You can still use HarmonyPriority since it doesn't rely on IDs.

**Comment by takahiro0327** [comment]
What? Other plugins?
Isn't it dangerous?
I would suggest not to touch them unless there is a problem like this one.

**Comment by ManlyMarco** [comment]
There is no risk in switching from random ID to a known one. It's a bug because it was meant to use GUID in the first place.

**Comment by takahiro0327** [comment]
I fixed this repository's.

There are so many, do you want to fix the others?
https://github.com/search?q=org%3AIllusionMods+CreateAndPatchAll&type=code
https://github.com/search?q=owner%3AManlyMarco%20CreateAndPatchAll&type=code

----

@ManlyMarco By the way, does your environment reproduce #54?

**Comment by ManlyMarco** [comment]
In most cases it's not really necessary to use GUID since nothing else will patch the same things, so I never bothered to fix it.
If you see any of this in IllusionFixes, BepisPlugins and similar common plugins then by all means do make PRs (be careful in case of shared GUIDs).

At the moment I don't have an environment to reproduce the issue, sorry.

**Comment by takahiro0327** [comment]
I had the person who first reported the bug try it. In his environment, the GUID fix fixed the bug.
From what I see in the log, it is probably the same as my environment.
I wonder if there is something else affecting the order of the patches. 

@ManlyMarco @ShalltyB 
GUID fix should not be a problem in terms of content, so if you two don't mind, I would like to have this PR merged.
What do you think?

**Review by ManlyMarco — APPROVED** [review]
Looks good to me. If others also approve then I'll merge it.

**Review by ShalltyB — APPROVED** [review]
It works well, thank you 🤗

**Comment by takahiro0327** [comment]
Thanks both for the reviews!

**Pull request merged**
