### PR TITLE
Match OCIItems with their index instead of their order by index.

### PR DESCRIPTION
**Pull request by krypto5863**
I'm not sure why this was done when a perfectly good index value was available but it gives the plugin room to break, and it did when I made ObjectMap which adds negative values to the dictionary thus causing the order to shift. Hoping this is a good change and I'm not missing something.

Another plugin that I bet does this is Timeline, but I don't really wanna mess with it.

### CODE REVIEW

**Review by ManlyMarco — COMMENTED** [review]
Your whitespace is whack, there's tabs mixed in.

Did you test this on existing old scenes? The more the better.

**Comment by krypto5863** [comment]
I did test on one or two, but I'll do a few more checks real quick.

**Comment by krypto5863** [comment]
Checked a good ten scenes in KKS real quick, most not mines. No issues that I can observe.

**Review by ManlyMarco — APPROVED** [review]
Looks good to me, please make a separate PR for the editor config file.

**Comment by ReafLife** [comment]
If you import another scene when have existing object, imported scene's PE data losted 
[unknown_2024.12.28-06.17.zip](https://github.com/user-attachments/files/18264432/unknown_2024.12.28-06.17.zip)

**Comment by krypto5863** [comment]
Oh, I suppose because imported items are being assigned a new key. Interesting challenge. I'll see what I can find.

**Pull request merged**
