### PR TITLE
Constraints support dynamic bone

### PR DESCRIPTION
**Pull request by takahiro0327**
#51 
If everything looks okay, please merge.

I am concerned about the intervention in the form of patching ExpressionBone.LateUpdate. I fear that there may have been some reason why it had to be done immediately after.

### CODE REVIEW

**Comment by ManlyMarco** [comment]
@ShalltyB Can you help review this?

**Comment by takahiro0327** [comment]
I wonder if anyone is using DynamicBone as a fixed bone for parents of constraints?
I'm starting to feel like there could be.
Could it be safer to add a checkbox and only LateUpdate the ones that are checked?
I don't know... What do you guys think?

**Comment by ShalltyB** [comment]
With this fix, if you link a DynamicBone to another DynamicBone it does stutter, it is more noticeable by lowering the time scale, as shown in these videos:

### Without fix:
https://github.com/IllusionMods/HSPlugins/assets/105353997/1972f437-177a-4998-b250-28e518375b7b

### With fix:

https://github.com/IllusionMods/HSPlugins/assets/105353997/ad6f92a1-20b0-4714-b03e-32a21085fc45

### Workaround of the current NodeConstraints:

Also, it does breaks other scenes that used a workaround to create links to DynamicBones.

#### Workaround example:
To link a Sphere to a Chain instead of doing: Chain parent linked to Sphere child.

It has to be: Creating a new Folder -> Folder parent linked to Sphere child -> Chain parent linked to Folder child.

I don't know if I can embed NSFW videos here to show an example of an Scene that I did with this workaround and now is broken with this fix.

**Comment by takahiro0327** [comment]
Green chain is shaking so much lol.

- Moving Transforms with Guides
- Constraint updates from Timeline.Update
- Physics calculation with DynamicBone
If only the above three are used, the system is rather stable. However
- Constraint update from LateUpdate by modification
I wonder if the system becomes unstable in terms of physical calculation when adding the following. I wonder if the warp of the first part of the green chain will increase.
I will look into this in detail on Saturday and Sunday.

By the way, in the version without the correction, there was a frame where the top of the green chain was not following the blue chain.
I think I am misunderstanding something. I don't think it should always be following.
image

----

Is this how workarounds work?

⛓ (chain)
│
└─ 📁 (folder)
'''''  │
'''''  └─ ⚽ (sphere)

Sorry, I don't know these things. What's the workaround?
Is there a web page that explains what it is?

----


By the way, what software do you use to record your videos, I'm using the standard Windows recording, but it doesn't get under 10MB with a clean quality like yours.

**Comment by ShalltyB** [comment]
Yeah, the stuttering may be due to DynamicBone calculations being interrupted. As for the frames where it stops following him completely, I think it's the garbage collector freezing Koikatsu as usual.

I record the screen using Camtasia at 30 fps with 50% encoding quality.

### Here is a video of the workaround using the lastest NodeConstraints (without any fix):

It may seem that the bug is not so problematic if you use this simple workaround, but it is quite annoying, especially if you work with animated scenes and multiple constraints, it becomes a nightmare.

https://github.com/IllusionMods/HSPlugins/assets/105353997/f6d04f1e-b6e1-4252-8720-53a8801ba062

**Comment by takahiro0327** [comment]
> DynamicBone calculations being interrupted.  

Does DynamicBone have a mechanism to cut off tracking when Time.deltaTime becomes large?

----

Thanks for the very detailed explanation of workaround!
That's great. Smart.
Sorry I should have tried it myself.

But I know the Sphere position is not broken in one frame, but I feel it will be broken in the next frame.
But it's not broken. I knew I am missing something.

- Timeline.Update
Sphere.pos <- Folder.pos
Folder.pos <- Chain.pos

- DynamicBone.Update
*Broken*Chain.pos <- Chain.pos

- ExpressionBone.LateUpdate
Sphere.pos <- Folder.pos
*Broken*Folder.pos <- *Broken*Chain.pos

- DynamicBone.LateUpdate
Chain.pos <- *Broken*Chain.pos

*Broken*Folder.pos keep? 

----

> I record the screen using Camtasia 

Thanks!

**Comment by takahiro0327** [comment]
I understand workarounds.
It doesn't matter if the folder location is broken. It's just used as a buffer.
If the chain position is not broken at the beginning of the frame, that's fine.

Next frame:

- Timeline.Update
*Broken*Sphere.pos <- *Broken*Folder.pos
Folder.pos <- Chain.pos

- DynamicBone.Update
*Broken*Chain.pos <- Chain.pos

- ExpressionBone.LateUpdate
Sphere.pos <- Folder.pos
*Broken*Folder.pos <- *Broken*Chain.pos

- DynamicBone.LateUpdate
Chain.pos <- *Broken*Chain.pos

I had a feeling this workaround would work with my modifications.
So I gave it a try. It still works.
I wonder if it's a more complicated case that breaks down, for example, if there is a character animation in between.

Workaround without fix:

https://github.com/IllusionMods/HSPlugins/assets/4230203/08050ae7-7b49-4ded-b656-1733bce13096

UFO inserted in folder. In the unmodified version it is broken.

Workaround with fix:

https://github.com/IllusionMods/HSPlugins/assets/4230203/5f619f92-d29c-4b0a-96cc-5f446dd6f9c9

**Comment by takahiro0327** [comment]
My fix that affects indiscriminately is no good. Shame.
I think the first idea or maybe VeryLateUpdate instead of skipping ExpressionBone.LateUpdate is the way to go.

I think the scenes that break with my fix are probably adjusted based on the assumption of a *Broken* Folder. Collider or the animation is affected from the broken position, or something.

**Comment by takahiro0327** [comment]
Modified to allow multiple methods to be tried at the same time.
image

Color,Method,NameInStudio
Green: original [Default]
Red: ShalltyB [TypeA]
Blue: takahiro0327 [TypeB]
Yellow: takahiro0327 + ApplyConstraints @ExpressionBone.LateUpdate [TypeC]

https://github.com/IllusionMods/HSPlugins/assets/4230203/d36c2d29-404b-438e-82f5-33d430ca1b47
https://github.com/IllusionMods/HSPlugins/assets/4230203/49cdc0fd-749e-4a81-bc08-053dbdd0bb31

Oh, I don't understand.

**Comment by takahiro0327** [comment]
I think ShalltyB's amendment is fine.


The pattern constrained by VeryLateUpdate was not going to solve the problem of DynamicBone going haywire.
It seems that we should not move the transform after DynamicBone.LateUpdate if we consider DynamicBone to be connected to DynamicBone.

The outburst was caused by some discrepancies between the internal state of the DynamicBone and the actual position.
I tried to add a correction for the misalignment, but it didn't give me good behavior.
I think it is because the correction gives extra positional energy.

It might be possible to solve only the case where two chains are connected by processing them in the following order, but it would be sterile, so I will not do it.

1. LateUpdate.DynamicBone(UpChain)
2. ApplyConstraints
3. LateUpdate.DynamicBone(DownChain)

**Comment by takahiro0327** [comment]
Memo:
The order of processing including mouse operation and animation is as follows

1. Update
1-1. Move Transform by mouse operation
1-2. ApplyNodesConstraints @ Timeline.Update

2. Animation
Character Animation

3. LateUpdate
3-1. ApplyConstraints @ ExpressionBone.LateUpdate
3-2. DynamicBone.LateUpdate

**Pull request closed without merging**
